# Generated by Django 4.1.1 on 2022-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=500)),
                ("date", models.DateField()),
                (
                    "doctor_type",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("ENT", "ENT"),
                            ("Cardiology", "Cardiology"),
                            ("Gynochology", "Gynocology"),
                            ("Neurology", "Neurology"),
                            ("Pediatric", "Pediatric"),
                            ("Orthopedics", "Orthopedics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mobile", models.PositiveIntegerField()),
            ],
        ),
    ]
