# Generated by Django 4.1.1 on 2022-09-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("med_name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("qty", models.IntegerField()),
                ("desc", models.CharField(max_length=100)),
            ],
        ),
    ]
