# Generated by Django 4.1.1 on 2022-10-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("d_name", models.CharField(max_length=50)),
                ("specialise", models.CharField(max_length=50)),
            ],
        ),
    ]
