# Generated by Django 4.1.1 on 2022-10-25 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor", "0003_med_assign_m_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
